import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/app/ConvexClientProvider";
import Navbar from "@/components/navbar";

const font = Montserrat({ subsets: ["latin"], weight: ['300', '400', '500', '600', '700', '800'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ConvexClientProvider>
          <Navbar />
          {children}
          <div className="shape1"></div>
          <div className="shape2"></div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
